POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: {{$dotenv AUTH_SCHEME}} {{$dotenv AUTH_TOKEN}}

{
  "title": "Test Blog 2",
  "author": "Test Author",
  "url": "http://test.com",
  "likes": 0
}
